# Generated by Django 6.0.2 on 2026-02-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
